In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
# 입력 : 2, 출력 : 3 선형 함수의 정의
l3 = nn.Linear(2, 3)

In [3]:
# 난수 시드값 고정
torch.manual_seed(123)

# 입력 : 1, 출력 : 1 선형 함수의 정의
l1 = nn.Linear(1, 1)

# 선형 함수 확인
print(l1)

Linear(in_features=1, out_features=1, bias=True)


In [4]:
# 파라미터명, 파라미터 값, shape 표시
for param in l1.named_parameters():
    print('name : ', param[0])
    print('tensor : ', param[1])
    print('shape : ', param[1].shape)

name :  weight
tensor :  Parameter containing:
tensor([[-0.4078]], requires_grad=True)
shape :  torch.Size([1, 1])
name :  bias
tensor :  Parameter containing:
tensor([0.0331], requires_grad=True)
shape :  torch.Size([1])


In [5]:
# 초깃값 설정
nn.init.constant_(l1.weight, 2.0)
nn.init.constant_(l1.bias, 1.0)

# 결과 확인
print(l1.weight)
print(l1.bias)

Parameter containing:
tensor([[2.]], requires_grad=True)
Parameter containing:
tensor([1.], requires_grad=True)


In [6]:
# 테스트 데이터 생성
# x_np를 넘파이 배열로 정의
x_np = np.arange(-2, 2.1, 1)

# 텐서 변수화
x = torch.tensor(x_np).float()

# (M, 1) 사이즈로 변경
x = x.view(-1, 1)

# 결과 확인
print(x.shape)
print(x)

torch.Size([5, 1])
tensor([[-2.],
        [-1.],
        [ 0.],
        [ 1.],
        [ 2.]])


In [7]:
# 1차 함수 테스트
y = l1(x)

print(y.shape)
print(y.data)

torch.Size([5, 1])
tensor([[-3.],
        [-1.],
        [ 1.],
        [ 3.],
        [ 5.]])


In [8]:
# 입력 : 2, 출력 : 1 선형 함수의 정의
l2 = nn.Linear(2, 1)

# 초깃값 설정
nn.init.constant_(l2.weight, 1.0)
nn.init.constant_(l2.bias, 2.0)

# 결과 확인
print(l2.weight)
print(l2.bias)

Parameter containing:
tensor([[1., 1.]], requires_grad=True)
Parameter containing:
tensor([2.], requires_grad=True)


In [9]:
# 2차원 넘파이 배열
x2_np = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# 텐서 변수화
x2 = torch.tensor(x2_np).float()

# 결과 확인
print(x2.shape)
print(x2)

torch.Size([4, 2])
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [10]:
# 함수 값 계산
y2 = l2(x2)

# shape 확인
print(y2.shape)

# 값 확인
print(y2.data)

torch.Size([4, 1])
tensor([[2.],
        [3.],
        [3.],
        [4.]])


In [12]:
# 입려 : 2, 출력 : 3 선형 함수 정의
l3 = nn.Linear(2, 3)

# 초깃값 설정
nn.init.constant_(l3.weight[0, :], 1.0)
nn.init.constant_(l3.weight[1, :], 2.0)
nn.init.constant_(l3.weight[2, :], 3.0)
nn.init.constant_(l3.bias, 2.0)

# 결과 확인
print(l3.weight)
print(l3.bias)

Parameter containing:
tensor([[1., 1.],
        [2., 2.],
        [3., 3.]], requires_grad=True)
Parameter containing:
tensor([2., 2., 2.], requires_grad=True)


In [13]:
# 함수 값 계산
y3 = l3(x2)

# shape 확인
print(y3.shape)

# 값 확인
print(y3.data)

torch.Size([4, 3])
tensor([[2., 2., 2.],
        [3., 4., 5.],
        [3., 4., 5.],
        [4., 6., 8.]])


In [14]:
# 모델 정의
class Net(nn.Module):
    def __init__(self, n_input, n_output):
        # 부모 클래스 nn.Module 초기화
        super().__init__()

        # 출력층 정의
        self.l1 = nn.Linear(n_input, n_output)

    # 예측 함수 정의
    def forward(self, x):
        x1 = self.l1(x)

        return x1

In [15]:
# 더미 입력
inputs = torch.ones(100, 1)

# 인스턴스 생성(1 입력, 1 출력 선형 모델)
n_input = 1
n_output = 1
net = Net(n_input, n_output)

# 예측
outputs = net(inputs)

In [16]:
# 손실 함수 : 평균 제곱 오차
criterion = nn.MSELoss() 